spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reai
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    validate-on-migrate: false

jwt:
  secret: dGVzdFNlY3JldDEyMzQ1Njc4OTA=

logging:
  level:
    root: INFO
    com.respiroc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.thymeleaf: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
    whitelabel:
      enabled: false